### ISSUE TITLE
Help to fix  'Pacific/Fiji' timezone ValueError: Extraneous characters at end of TZ string

### ISSUE THREAD

**Issue by adnankaya** [mfogel/django-timezone-field#92]
Python 3.9.13
Django 4.0.7
django-timezone-field==5.0

timezone_field/fields.py:41
```python
    # NOTE: these defaults are excluded from migrations. If these are changed,
    #       existing migration files will need to be accomodated.
    default_max_length = 63
    default_pytz_tzs = [pytz.timezone(tz) for tz in pytz.common_timezones]
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones] # ERROR raises HERE!
```
Captured ERROR while debugging

```bash
(Pdb) ZoneInfo(pytz.common_timezones[400])
zoneinfo.ZoneInfo(key='Pacific/Fakaofo')
(Pdb) ZoneInfo(pytz.common_timezones[401])
ValueError: Extraneous characters at end of TZ string: b'<+12>-12<+13>,M11.1.0,M1.2.2/123'
(Pdb) pytz.common_timezones[401]
'Pacific/Fiji'
(Pdb) ZoneInfo(pytz.common_timezones[402])
zoneinfo.ZoneInfo(key='Pacific/Funafuti')
```
---
#### Full Error 
```bash
Traceback (most recent call last):
  File "/home/myuser/myproject/myapp/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/myuser/myproject/env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/django_celery_beat/models.py", line 8, in <module>
    import timezone_field
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/timezone_field/__init__.py", line 1, in <module>
    from timezone_field.fields import TimeZoneField
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/timezone_field/fields.py", line 11, in <module>
    class TimeZoneField(models.Field):
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in TimeZoneField
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
  File "/home/myuser/myproject/env/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in <listcomp>
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
ValueError: Extraneous characters at end of TZ string: b'<+12>-12<+13>,M11.1.0,M1.2.2/123'
```

**Comment by mfogel** [comment]
I can't reproduce this on a mac, with python 3.9.13.

```
Python 3.9.13 (main, Jun 18 2023, 13:22:51)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoneinfo import ZoneInfo
>>> ZoneInfo("Pacific/Fiji")
zoneinfo.ZoneInfo(key='Pacific/Fiji')
```

But in any case, this appears to either be a bug with `ZoneInfo` or perhaps with the backing store of timezones - be that either an installed copy of `tzdata` or the OS's timezone list.
